### ISSUE TITLE
craftcms/commerce-omnipay 2.x.x

### ISSUE THREAD

**Issue by MarcelWeidum** [verbb/commerce-payflow#2]
### Description
1.0.2 version requires craftcms/commerce-omnipay [1.0.0, 1.0.1, 1.0.2] but version 2.x.x is out. When does payflow supports this version?

**Comment by engram-design** [comment]
I'll certainly need to test this out, and not sure of the amount of changes, so no ETA. Looking into it.

**Comment by engram-design** [comment]
Added support in [2.0.0](https://github.com/verbb/commerce-payflow/releases/tag/2.0.0)
